minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - ioredis@5.10.0

shellEmulator: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 267840

allowBuilds:
  '@parcel/watcher': true
  bcrypt: true
  better-sqlite3: false
  core-js: false
  esbuild: true
  unrs-resolver: false
  vue-demi: true
