minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - ioredis@5.10.0

shellEmulator: true

strictPeerDependencies: true

trustPolicy: no-downgrade
overrides:
  reka-ui@2.6.0: 2.6.1

ignoredBuiltDependencies:
  - core-js
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - bcrypt
  - better-sqlite3
  - esbuild
  - vue-demi
